const ACTION_TYPE = {
  INIT_FIELD: "INIT_FIELD",
  INIT_FIRST_LEVEL: "INIT_FIRST_LEVEL",
  ADD_PLAYER_TURN: "ADD_PLAYER_TURN",
  SKIP_TURN: "SKIP_TURN",
  SET_CURRENT_BUILDING: "SET_CURRENT_BUILDING",
  CANCEL_BUILDING: "CANCEL_BUILDING",
  MOCK_AI_TURN: "MOCK_AI_TURN",
  RESOLVE_TURN: "RESOLVE_TURN",
  CREATE_BUILDING: "CREATE_BUILDING",
  EXEC_ACTION: "EXEC_ACTION",
  START_TURN_RESOLVE: "START_TURN_RESOLVE",
  END_TURN_RESOLVE: "END_TURN_RESOLVE",
  ADD_RESOURCE_TEAM: "ADD_RESOURCE_TEAM",
};

export default ACTION_TYPE;
