export const UNIT_TYPE = {
  MAIN_BASE: "MAIN_BASE",
  GENERATOR: "GENERATOR",
  GATHERER: "GATHERER",
  DISC_THROWER: "DISC_THROWER",
  SUN_CANNON: "SUN_CANNON",
  MINERAL_RESOURCE: "MINERAL_RESOURCE"
};
